services:

  mongo:
    image: mongo:7.0
    container_name: meshcentral-mongo
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    volumes:
      - ./db:/data/db

    networks:
      - internal


  meshcentral:
    build:
      context: .
      dockerfile_inline: |
        FROM ghcr.io/ylianst/meshcentral:1.2.1

        COPY custom/win-userconsent-defaultchecked.js \
          /opt/meshcentral/meshcentral/agents/modules_meshcore/win-userconsent-defaultchecked.js

        RUN sed -i \
          "s/require('win-userconsent')/require('win-userconsent-defaultchecked')/g" \
          /opt/meshcentral/meshcentral/agents/meshcore.js \
          && grep -q "require('win-userconsent-defaultchecked')" \
          /opt/meshcentral/meshcentral/agents/meshcore.js

        COPY custom/notifybar-desktop.js \
          /opt/meshcentral/meshcentral/agents/modules_meshcore/notifybar-desktop-custom.js

        RUN sed -i \
          "s/require('notifybar-desktop')/require('notifybar-desktop-custom')/g" \
          /opt/meshcentral/meshcentral/agents/meshcore.js \
          && grep -q "require('notifybar-desktop-custom')" \
          /opt/meshcentral/meshcentral/agents/meshcore.js

        RUN sed -i \
          "s/currentTranslation\['allow'\]/'Permite'/g; \
          s/currentTranslation\['deny'\]/'Refuză'/g" \
          /opt/meshcentral/meshcentral/agents/meshcore.js \
          && grep -q "'Permite'" \
          /opt/meshcentral/meshcentral/agents/meshcore.js \
          && grep -q "'Refuză'" \
          /opt/meshcentral/meshcentral/agents/meshcore.js

        COPY custom/win-session-state-tracker.js \
          /opt/meshcentral/meshcentral/agents/modules_meshcore/win-session-state-tracker.js

        RUN sed -i \
          "/var promise = require('promise');/a try { require('win-session-state-tracker'); } catch (ex) { }" \
          /opt/meshcentral/meshcentral/agents/meshcore.js \
          && grep -q "require('win-session-state-tracker')" \
          /opt/meshcentral/meshcentral/agents/meshcore.js

        COPY custom/patch-session-timeline.js \
          /tmp/patch-session-timeline.js

        RUN node /tmp/patch-session-timeline.js \
          && rm /tmp/patch-session-timeline.js

    container_name: meshcentral
    restart: unless-stopped

    depends_on:
      - mongo

    ports:
      - "4434:443"
      - "4433:4433"

    environment:
      NODE_ENV: production
      MINIFY: "false"
      HOSTNAME: ${MESHCENTRAL_HOSTNAME}

    volumes:
      - ./data:/opt/meshcentral/meshcentral-data
      - ./files:/opt/meshcentral/meshcentral-files
      - ./backups:/opt/meshcentral/meshcentral-backups

    networks:
      - internal


networks:
  internal:
    driver: bridge
